# Generated by Django 4.2.2 on 2023-06-11 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('details', models.TextField(max_length=200)),
                ('category', models.CharField(blank=True, choices=[('education', 'education'), ('entertainment', 'entertainment'), ('sports', 'sports'), ('fashon', 'fashon')], max_length=50, null=True)),
                ('mutliImage', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('totalTarget', models.DecimalField(decimal_places=0, max_digits=6)),
                ('tag', models.CharField(blank=True, choices=[('education', 'education'), ('entertainment', 'entertainment'), ('sports', 'sports'), ('fashon', 'fashon')], max_length=50, null=True)),
                ('startDate', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
