# Generated by Django 4.2.2 on 2023-06-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_multipleimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleImage',
        ),
    ]
