# Generated by Django 4.2.2 on 2023-06-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_login_user_login_email_alter_login_password'),
        ('projects', '0003_delete_multipleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='userEmail',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
            preserve_default=False,
        ),
    ]
