# Generated by Django 4.1.4 on 2023-06-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='userEmail',
        ),
    ]
