# Generated by Django 4.1.4 on 2023-06-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(default=True, max_length=254),
            preserve_default=False,
        ),
    ]
