# Generated by Django 4.1.4 on 2023-06-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mutliImage',
            field=models.ImageField(blank=True, upload_to='photo/%y/%m/%d'),
        ),
    ]
