# Generated by Django 4.1.4 on 2023-06-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default=True, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
